// Code generated by hamr gen static; DO NOT EDIT.

package components

// StaticManifest maps original asset paths to fingerprinted paths.
var StaticManifest = map[string]string{
	"css/base/reset.css": "css/base/reset.6820a2208df9.css",
	"css/base/utilities.css": "css/base/utilities.b1c22fd769f0.css",
	"css/base/variables.css": "css/base/variables.754b319d5aa9.css",
	"css/components/alerts.css": "css/components/alerts.aab5e3ea60f2.css",
	"css/components/buttons.css": "css/components/buttons.81d0bf392c13.css",
	"css/components/forms.css": "css/components/forms.e5693849894f.css",
	"css/layout/footer.css": "css/layout/footer.db95d2a22f24.css",
	"css/layout/header.css": "css/layout/header.b9a95c03c6f9.css",
	"css/pages/home.css": "css/pages/home.90387a6ff80c.css",
	"js/htmx.min.js": "js/htmx.min.e209dda5c823.js",
	"js/idiomorph.min.js": "js/idiomorph.min.cfbc37ff80a7.js",
	"js/main.js": "js/main.afcd9f43e788.js",
}
