services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    labels:
      role: database
    volumes:
      - ./.docker-mount:/var/lib/postgresql/data
    restart: always
    user: "${UID}:${GID}"  # Or hardcode a non-root user like "1000:1000"
    ports:
      - "5432:5432"

  backend:
    image: nginx
    depends_on:
      - db
    environment:
      SERVICE: backend
    labels:
      role: backend
    restart: on-failure
    ports:
      - "8080:80"

  frontend:
    image: nginx
    depends_on:
      - backend
    environment:
      SERVICE: frontend
    labels:
      role: frontend
    restart: always
    ports:
      - "3000:80"
